<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function findAllItemOnly() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i.id, i.sku, i.name, i.description, i.price FROM AppBundle:Item i'
            )
            ->getResult();
    }
}
