<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function findAllByUser($user_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT o FROM AppBundle:Order o where o.user = :user'
            )
            ->setParameter('user', $user_id)
            ->getResult();
    }
    
    public function findAllByDriver($driver_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT o FROM AppBundle:Order o where o.driver = :driver'
            )
            ->setParameter('driver', $driver_id)
            ->getResult();
    }
    
    public function findAllFree()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT o FROM AppBundle:Order o where o.driver is null'
            )
            ->getResult();
    }
}
